In [1]:
import yfinance as yf
import numpy as np
import pandas as pd

In [2]:
stocks = pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[2].Symbol

In [3]:
stocks.head(5)

0      ADANIENT
1    ADANIPORTS
2    APOLLOHOSP
3    ASIANPAINT
4      AXISBANK
Name: Symbol, dtype: object

In [4]:
stocks = stocks + '.NS'

In [5]:
stocks = stocks.to_list()

In [6]:
df = yf.download(stocks, start='2015-1-1')['Close']

[*********************100%***********************]  50 of 50 completed

In [7]:
df

,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,UPL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-01,75.104774,319.549988,1125.900024,749.150024,503.049988,2452.149902,128.660004,349.970001,333.206940,218.066666,...,822.200012,150.699997,493.160370,38.533432,1272.775024,648.637512,379.799988,2662.500000,227.733337,207.150055
2015-01-02,75.472641,319.350006,1127.849976,775.049988,514.299988,2451.750000,127.565002,344.375000,335.181000,214.800003,...,826.250000,152.500000,506.368683,39.133656,1289.724976,651.812500,382.799988,2742.100098,234.833328,208.987549
2015-01-05,76.721832,323.799988,1131.599976,775.000000,517.549988,2460.699951,125.870003,343.475006,327.743774,215.216660,...,826.750000,152.949997,518.241333,39.700535,1270.125000,640.937500,385.899994,2747.699951,230.466660,209.362549
2015-01-06,76.139381,321.850006,1097.900024,756.500000,499.049988,2441.500000,122.959999,342.584991,325.172882,213.050003,...,808.549988,148.149994,496.079071,37.776009,1223.300049,634.062500,372.700012,2670.600098,219.300003,204.468796
2015-01-07,75.464973,321.100006,1106.500000,771.700012,498.649994,2447.199951,122.855003,349.559998,325.953308,214.983337,...,809.799988,148.449997,488.609192,37.051926,1208.849976,631.099976,374.600006,2660.050049,215.366669,202.912552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-12,2484.800049,742.099976,4924.750000,3194.750000,974.200012,4769.649902,1466.000000,7097.700195,836.349976,371.649994,...,985.450012,800.750000,564.150024,109.500000,3246.899902,1074.750000,2852.600098,8198.599609,678.950012,395.600006
2023-06-13,2462.550049,737.849976,4951.049805,3262.850098,985.849976,4755.950195,1486.199951,7166.750000,834.349976,373.600006,...,988.099976,819.900024,562.200012,111.150002,3243.699951,1079.400024,2912.500000,8276.299805,682.250000,395.549988
2023-06-14,2457.149902,739.349976,5009.000000,3270.199951,977.700012,4730.200195,1480.400024,7096.850098,827.950012,373.549988,...,986.700012,862.500000,570.299988,113.800003,3251.050049,1077.599976,2907.050049,8358.299805,682.750000,396.450012
2023-06-15,2485.649902,739.500000,5218.750000,3294.350098,977.150024,4721.549805,1474.699951,7126.600098,829.700012,378.899994,...,988.400024,865.000000,568.450012,113.750000,3216.300049,1081.500000,2908.000000,8333.200195,680.799988,388.950012
2023-06-16,2509.600098,747.400024,5200.049805,3316.850098,981.549988,4641.950195,1508.599976,7203.200195,837.799988,376.799988,...,992.000000,862.750000,569.799988,114.250000,3174.899902,1077.199951,2954.300049,8333.250000,690.849976,381.299988

In [8]:
returns_df = df.pct_change()

In [9]:
returns_df

,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,UPL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-02,0.004898,-0.000626,0.001732,0.034572,0.022364,-0.000163,-0.008511,-0.015987,0.005924,-0.014980,...,0.004926,0.011944,0.026783,0.015577,0.013317,0.004895,0.007899,0.029897,0.031177,0.008870
2015-01-05,0.016552,0.013934,0.003325,-0.000064,0.006319,0.003650,-0.013287,-0.002613,-0.022189,0.001940,...,0.000605,0.002951,0.023447,0.014486,-0.015197,-0.016684,0.008098,0.002042,-0.018595,0.001794
2015-01-06,-0.007592,-0.006022,-0.029781,-0.023871,-0.035745,-0.007803,-0.023119,-0.002591,-0.007844,-0.010067,...,-0.022014,-0.031383,-0.042764,-0.048476,-0.036866,-0.010726,-0.034206,-0.028060,-0.048452,-0.023375
2015-01-07,-0.008858,-0.002330,0.007833,0.020093,-0.000802,0.002335,-0.000854,0.020360,0.002400,0.009075,...,0.001546,0.002025,-0.015058,-0.019168,-0.011812,-0.004672,0.005098,-0.003950,-0.017936,-0.007611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-12,0.013728,0.009729,-0.000396,0.004465,-0.000564,0.005534,-0.000341,0.008604,0.003419,0.033941,...,0.001524,-0.000312,0.003290,0.005510,0.011716,0.011006,-0.008222,0.005562,-0.001911,-0.004279
2023-06-13,-0.008954,-0.005727,0.005340,0.021316,0.011958,-0.002872,0.013779,0.009728,-0.002391,0.005247,...,0.002689,0.023915,-0.003457,0.015069,-0.000986,0.004327,0.020998,0.009477,0.004860,-0.000126
2023-06-14,-0.002193,0.002033,0.011705,0.002253,-0.008267,-0.005414,-0.003903,-0.009753,-0.007671,-0.000134,...,-0.001417,0.051958,0.014408,0.023842,0.002266,-0.001668,-0.001871,0.009908,0.000733,0.002275
2023-06-15,0.011599,0.000203,0.041875,0.007385,-0.000563,-0.001829,-0.003850,0.004192,0.002114,0.014322,...,0.001723,0.002899,-0.003244,-0.000439,-0.010689,0.003619,0.000327,-0.003003,-0.002856,-0.018918
2023-06-16,0.009635,0.010683,-0.003583,0.006830,0.004503,-0.016859,0.022988,0.010748,0.009763,-0.005542,...,0.003642,-0.002601,0.002375,0.004396,-0.012872,-0.003976,0.015922,0.000006,0.014762,-0.019668

In [10]:
monthly_returns = (returns_df + 1).resample('M').prod()

In [11]:
monthly_returns

,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,UPL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-31,1.280204,1.067282,1.166667,1.144964,1.169069,0.975348,1.125097,1.157399,1.029760,1.144681,...,1.116213,1.053086,1.173939,0.965385,0.975055,1.105587,1.133755,1.179474,1.078308,1.098027
2015-02-28,1.133987,1.015247,0.991321,0.941008,0.964377,0.899151,0.982453,1.013961,0.950495,0.993857,...,0.957668,0.983302,0.982910,0.898066,1.072642,0.988583,1.011031,0.995367,1.139677,1.078724
2015-03-31,0.865045,0.890108,1.051492,1.005142,0.987746,0.937735,0.994656,1.000329,1.107264,1.089419,...,1.164979,0.953541,0.956620,0.903322,0.959284,0.888231,0.899506,0.920692,1.053240,0.961103
2015-04-30,1.095637,1.030337,0.830522,0.939788,1.013567,0.966305,1.014386,0.984386,0.968980,0.943204,...,0.916935,0.954973,0.933663,1.137648,0.964663,0.986740,0.977528,0.928490,1.109691,0.856484
2015-05-31,1.047612,1.019839,1.066306,1.032264,1.030997,1.188566,1.064255,1.042591,1.116767,1.111670,...,1.029025,1.029205,0.947664,0.911614,1.059504,0.892251,0.988245,1.113469,1.126363,1.042889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28,0.458607,0.967028,1.034247,1.037768,0.968449,0.958869,0.994376,1.038343,0.963586,0.924545,...,0.924698,0.980535,0.930546,0.868421,0.986349,1.083990,0.998170,1.024804,0.916799,0.970415
2023-03-31,1.283462,1.066588,0.979383,0.976262,1.017060,1.061059,0.948760,0.918956,1.009094,1.084922,...,1.027702,0.990983,1.000238,1.005291,0.967717,1.001454,1.059887,1.049695,1.033780,0.943677
2023-04-30,1.099689,1.078177,1.047044,1.050948,1.001747,1.140859,1.069601,1.118102,1.067156,1.038629,...,1.004628,1.077590,1.152448,1.033014,1.004164,0.929074,1.050479,0.991348,1.031561,1.054073
2023-05-31,1.295280,1.084471,1.023983,1.100126,1.063779,1.030506,1.071162,1.113016,1.063305,1.016499,...,0.987546,1.045559,1.085266,0.980083,1.021822,1.089724,1.068664,1.041535,0.925436,1.048442
2023-06-30,1.006517,1.011572,1.125077,1.038804,1.072908,1.016378,1.039661,1.030523,0.985763,1.036589,...,1.017071,1.080260,1.082652,1.079868,0.965162,0.965622,1.046418,1.058856,1.008393,0.944630